services:
  - type: web
    name: blinkit-backend
    env: python
    plan: free
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: database_url
        fromDatabase:
          name: blinkit-postgres
          property: connectionString
      - key: mongodb_url
        value: mongodb+srv://blinkit_admin:Z#if3uRQk_KH#9U>@cluster0.t9ajn7r.mongodb.net/?appName=Cluster0
      - key: redis_url
        fromService:
          type: redis
          name: blinkit-redis
          property: connectionString
      - key: jwt_secret_key
        generateValue: true
      - key: cors_origins
        value: https://your-frontend-domain.vercel.app,http://localhost:3000
